### ISSUE TITLE
extends()

### ISSUE THREAD

**Issue by jeregrine** [mhanberg/schematic#11]
Ability to extend a map. I can accomplish this now by doing something like 

```elixir

base = %{
  "type" => oneof(["thing", "doodad"]),
  "id" => int()
}
base_schema = map(base)

thingy = map(Map.merge(base, %{
  "type" => "thing",
  "description" => str()
}))

doodad = map(Map.merge(base, %{
  "type" => "doodad",
  "size" => int()
}))

doodad = extend(base_schema, %{
  "type" => "doodad",
  "size" => int()
}))
```

Maybe I'm missing a better way to do accomplish this. But its pretty common coming from typescript interfaces.

**Comment by mhanberg** [comment]
Yeah this makes sense.

In my first use case, which was generated from a JSON Schema that mostly mapped from TypeScript, the way i did this was more or less what you have here.

My first thought would be to have the map schematic take a map schematic as it's first arg and the blueprint as the second.

```elixir
base = map(%{
  "type" => oneof(["thing", "doodad"]),
  "id" => int()
})

thingy = map(base, %{
  "type" => "thing",
  "description" => str()
})
```

in this case, are you ever actually unifying any input against the base schematic?

**Comment by jeregrine** [comment]
Yea a couple times. https://atproto.com/guides/lexicon#schema-format This is what I am reimplementing from typescript. And unifying against their own repo(which is finding bugs lol)

**Comment by jeregrine** [comment]
here is my gist of WIP https://gist.github.com/jeregrine/95d9d1fd14c0775318f9c9db7d50165a
