### ISSUE TITLE
Property Based Tests

### ISSUE THREAD

**Issue by clark-lindsay** [mhanberg/schematic#8]
## Description

adding property based tests (with [streamdata](https://hexdocs.pm/stream_data/StreamData.html)) will improve the confidence that the test suite provides, and maybe expose bugs that are hard to find through case-based hand-written tests.

overall the existing code base (and test suite) should become easier to extend, and make the library more reliable as a dependency

**Comment by clark-lindsay** [comment]
i've started working on this over [here](https://github.com/clark-lindsay/schematic/tree/add-property-based-tests)

**Comment by mhanberg** [comment]
Feel free to open a draft PR if you'd like.
